alias mpvnovideo="mpv --vid=no --save-position-on-quit"
alias yaycache="yay -Sc --aur"
alias rede="sudo nethogs -p"
alias rede2="sudo bandwhich"
alias neo="fastfetch"
alias atualizar="flatpak update && flatpak remove --unused && archnews && sudo pacman -Syu && yay --removemake --needed -Sua --devel"
alias omzsh="echo -e '\e[0;34mzsh-syntax-highlighting\e[0m' && git -C $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting pull && echo -e '\e[0;34mzsh-autosuggestions\e[0m' && git -C $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions pull && echo -e '\e[0;34mzsh-completions\e[0m' && git -C $HOME/.oh-my-zsh/custom/plugins/zsh-completions pull && omz update"
alias limpar="find ~/.cache/ -type f -atime +365 -delete && sudo paccache -rk2 && yay -Yc"
alias scanports="rustscan -a 127.0.0.1 --ulimit 5000"
alias dados="yay -Ps"
alias size="du -ch --max-depth=1 . | sort -h"
alias xls="eza -a --icons --color=always --group-directories-first"
alias xll="eza -lag --icons --color=always --header --group-directories-first --octal-permissions"
alias xla="eza -las age --icons --color=always --group-directories-first"
alias xltree="eza -la --icons --color=always --group-directories-first --octal-permissions --header --tree"
alias cat="bat --theme=Dracula"
alias cpu-info="grep 'cpu MHz' /proc/cpuinfo && sudo x86_energy_perf_policy && cat /sys/devices/system/cpu/intel_pstate/*"
alias boot="systemd-analyze && systemctl list-timers"
alias fail2ban="sudo fail2ban-client status && sudo fail2ban-client status sshd"
alias report-audit="sudo aureport -n"
alias dic-pt="aspell -x --lang=pt_BR -c"
alias dic-en="aspell -x --lang=en -c"
alias ram="watch -n 1 free -h"
alias atalhos="glow -p $HOME/.atalhos.md"
alias pacman.log="tspin /var/log/pacman.log"
alias dirty="cat /proc/vmstat | egrep 'dirty|writeback'"
alias progress="progress -m"
alias instalar="sudo pacman -Sy"
alias remover="sudo pacman -R"
alias mirror="rankmirrors -t /etc/pacman.d/mirrorlist"
alias turbo="sudo turbostat --quiet --interval 1 --cpu 0-7 --show 'PkgWatt','Busy%','Core','CoreTmp'"
alias hist="history | fzf"
alias nvidia="watch -n 0.5 nvidia-smi"
alias sudo="run0 --background= "
alias nano="micro"
alias hist-pacotes="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -200 | nl"
alias fixpacman="sudo rm /var/lib/pacman/db.lck"
alias tb="nc termbin.com 9999"
alias tcpporta="sudo tcpdump -i any -n -v port "
alias archwiki="wiki-search-html"
